# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org/'
platform :ios, '12.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pro_flutter_module_path = '../yandexPro'
  load File.join(pro_flutter_module_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(pro_flutter_module_path)

  pod 'YandexMapsMobile', '4.6.1-lite'
end

post_install do |installer|
    flutter_post_install(installer) if defined?(flutter_post_install)
end
