name: Setup Flutter Environment
description: Setup Flutter environment

runs:
  using: 'composite'
  steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
