name: PR Checks

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '**.sh'

env:
  gradleFlags: --parallel --stacktrace --no-configuration-cache --no-daemon

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/init-gradle
      - name: Setup Flutter
        uses: ./.github/actions/init-flutter
      - name: Build Flutter Module
        uses: ./.github/actions/build-flutter-android
      - name: Run Checks
        run: ./gradlew check $gradleFlags
      - name: Upload check reports
        uses: actions/upload-artifact@v4
        with:
          name: check-reports
          path: |
            **/build/reports/*  
            

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/init-gradle
      - name: Setup Flutter
        uses: ./.github/actions/init-flutter
      - name: Build Flutter Module
        uses: ./.github/actions/build-flutter-android
        with:
          params: --no-debug --no-profile
      - name: Build with Gradle
        run: ./gradlew :composeApp:assembleRelease $gradleFlags
      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: composeApp/build/outputs/apk/release/composeApp-release-unsigned.apk